receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  prometheus:
    config:
      scrape_configs:
        - job_name: "task-manager"
          static_configs:
            - targets: ["host.docker.internal:3000"]
          metrics_path: "/api/metrics"
          scrape_interval: 30s
          scrape_timeout: 10s
        - job_name: "gateway"
          static_configs:
            - targets: ["host.docker.internal:3002"]
          metrics_path: "/api/metrics"
          scrape_interval: 30s
          scrape_timeout: 10s

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
  # Removed resource processor that was overriding service names
  # Each service should set its own service name

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"
    namespace: ""
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  otlp/tempo:
    endpoint: tempo:14250
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlp/tempo, debug]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlphttp/loki, debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, memory_limiter]
      exporters: [prometheus, debug]
