receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  prometheus:
    config:
      scrape_configs:
        - job_name: 'task-manager'
          static_configs:
            - targets: ['host.docker.internal:3000']
          metrics_path: '/api/metrics'
          scrape_interval: 30s
          scrape_timeout: 10s

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
  resource:
    attributes:
      - key: service.name
        value: task-manager
        action: upsert

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: '0.0.0.0:9464'
    namespace: 'task_manager'
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  otlp/traces:
    endpoint: 'tempo:4317'
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: 'http://loki:3100/otlp'
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [otlp/traces, debug]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [otlphttp/loki, debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, memory_limiter, resource]
      exporters: [prometheus, debug]
