receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
  resource:
    attributes:
      - key: environment
        value: 'development'
        action: upsert

exporters:
  logging:
    verbosity: detailed
  otlp/traces:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/metrics:
    endpoint: prometheus:9090
    tls:
      insecure: true
  loki:
    endpoint: 'http://loki:3100/loki/api/v1/push'
    format: 'json'
    labels:
      resource:
        service.name: 'EXPORTER'
        service.version: '1.0.0'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlp/traces, logging]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlp/metrics, logging]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [loki, logging]

  extensions: []
